Models/ErrorViewModel.cs
using System;

namespace proyectoCRUD.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Libro.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace proyectoCRUD.Models
{
    public class Libro
    {
        //Propiedades

        [Key] //Permite establecer una llave primaria
        public int Id { get; set; }

        [Display(Name = "Titulo")]

        public string Titulo { get; set; }
            

        public string Descripcion { get; set; }
        [DataType(DataType.Date)] //Establecemos el formato fecha corta
        public DateTime FechaPublicacion { get; set; }

        [Required(ErrorMessage ="El nombre del autor es requerido")]

        public string Autor { get; set; }

        [Required(ErrorMessage = "El precio del libro es requerido")]

        public int PrecioLibro { get; set; }


        
        
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using proyectoCRUD.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace proyectoCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using proyectoCRUD.Data;
using proyectoCRUD.Models;
using System.Collections.Generic;

namespace proyectoCRUD.Controllers
{
    public class LibrosController : Controller
    {

        //Instanciamos el contexto
        private readonly AplicationDbContext _context;

        //Creamos el constructor
        public LibrosController(AplicationDbContext context) 
        {
            _context = context;


        }

        public IActionResult Index()
        {

            //Instanciamos la clase libros
            IEnumerable<Libro> listaLibros = _context.Libro;

            //Retorno de la lista
            return View(listaLibros);
        }

        //Creamos el metodo
        public IActionResult Create() {
            //Mostramos la vista
            return View();
        }

        //Creamos el metodo crear-post
        [HttpPost]

        public IActionResult Create(Libro libro) 
        { 
            if(ModelState.IsValid)
            {
                //Accederemos a la base de datos
                _context.Libro.Add(libro);

                //Guardamos los cambios
                _context.SaveChanges();

                //Indicamos con mensaje al usuario que el registro se ha guardado
                TempData["mensaje"] = "Registro Guardado Exitosamente!";

                //Redireccionamos el index
                return RedirectToAction("Index");
            }

            return View();

        }

        //Creamos el metodo para EDITAR
        public IActionResult Edit(int? id)
        {
            //Evaluamos si el registro es distinto de vacio
            if (id == null || id==0) {

                return NotFound();
            }

            //Obtener libro
            var libro = _context.Libro.Find(id);

            //Evaluamos el identificador
            if(libro == null)
            {
                //En caso de no encontrar el identificador
                return NotFound();
            }

            return View(libro);
        }

        //Metodo HTTP-POST-EDIT
        [HttpPost]

        public IActionResult Edit(Libro libro) { 

            if (ModelState.IsValid)
            {
                _context.Libro.Update(libro);

                _context.SaveChanges();

                TempData["mensaje"] = "EL REGISTRO SE HA ACTUALIZADO CORRECTAMENTE!";

                return RedirectToAction("Index");
            }
            return View();
        }


        //Creamos el metodo para ELIMINAR
        public IActionResult Delete(int? id)
        {
            //Evaluamos si el registro es distinto de vacio
            if (id == null || id == 0)
            {

                return NotFound();
            }

            //Obtener libro
            var libro = _context.Libro.Find(id);

            //Evaluamos el identificador
            if (libro == null)
            {
                //En caso de no encontrar el identificador
                return NotFound();
            }

            return View(libro);
        }

        //METODO HTTP-POST-DELETE
        [HttpPost]

        //Colocamos una validacion para el formulario
        [ValidateAntiForgeryToken]

        public IActionResult DeleteLibro(int? id) 
        {

            //Obtenemos el identificador del libro
            var libro = _context.Libro.Find(id);

            //Realizamos la validacion para el registro
            if (libro == null)
            {
                return NotFound();
            }

            //Realizamos la eliminacion del registro
            _context.Libro.Remove(libro);

            //Guardamos cambios
            _context.SaveChanges();

            TempData["mensaje"] = "EL REGISTRO HA SIDO ELIMINADO CORRECTAMENTE!";

            //Redireccionamos al Index
            return RedirectToAction("Index");
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

  <div class ="text-center">
        <h1 class="display-4">BIENVENIDOS AL CURSO DE PROGRAMACION APLICADA</h1>
        <h1>UES</h1>
         <a href= "https://www.ues.mx/">Universidad Estatal de Sonora</a>
    </div>

Views/Libros/Create.cshtml
@model proyectoCRUD.Models.Libro

@{
    ViewData["Title"] = "Crear nuevo libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class = "container">

    <div class="row">
        <div class="col-sm-12">
            <h3>CREAR NUEVO LIBRO</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <form method="post" asp-action="Create">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaPublicacion" class="control-label"></label>
                    <input asp-for="FechaPublicacion" class="form-control" />
                    <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PrecioLibro" class="custom-control-label"></label>
                    <input asp-for="PrecioLibro" class="form-control" />
                    <span asp-validation-for="PrecioLibro" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Crear libro" class="btn btn-primary"/>
                </div>


            </form>

        </div>
    </div>
</div>

@section Scripts{
    @{<partial name="_ValidationScriptsPartial" /> }
}

Views/Libros/Delete.cshtml
@model proyectoCRUD.Models.Libro

@{
    ViewData["Title"] = "Eliminar registro libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class = "container">

    <div class="row">
        <div class="col-sm-12">
            <h3>ELIMINAR LIBRO</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-10">
            <form method="post" asp-action="DeleteLibro">

                <input type="hidden" asp-for="Id"/>

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" readonly />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control"readonly />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaPublicacion" class="control-label"></label>
                    <input asp-for="FechaPublicacion" class="form-control"readonly />
                    <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control"readonly />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PrecioLibro" class="custom-control-label"></label>
                    <input asp-for="PrecioLibro" class="form-control"readonly />
                    <span asp-validation-for="PrecioLibro" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Eliminar libro" class="btn btn-primary"/>
                </div>


            </form>

        </div>
    </div>
</div>

@section Scripts{
    @{<partial name="_ValidationScriptsPartial" /> }
}

Views/Libros/Edit.cshtml
@model proyectoCRUD.Models.Libro

@{
    ViewData["Title"] = "Editar registro libro";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class = "container">

    <div class="row">
        <div class="col-sm-12">
            <h3>EDITAR LIBRO</h3>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <form method="post" asp-action="Edit">

                <input type="hidden" asp-for="Id"/>

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group">
                    <label asp-for="Titulo" class="control-label"></label>
                    <input asp-for="Titulo" class="form-control" />
                    <span asp-validation-for="Titulo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Descripcion" class="control-label"></label>
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="FechaPublicacion" class="control-label"></label>
                    <input asp-for="FechaPublicacion" class="form-control" />
                    <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Autor" class="control-label"></label>
                    <input asp-for="Autor" class="form-control" />
                    <span asp-validation-for="Autor" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="PrecioLibro" class="custom-control-label"></label>
                    <input asp-for="PrecioLibro" class="form-control" />
                    <span asp-validation-for="PrecioLibro" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Editar libro" class="btn btn-primary"/>
                </div>


            </form>

        </div>
    </div>
</div>

@section Scripts{
    @{<partial name="_ValidationScriptsPartial" /> }
}

Views/Libros/Index.cshtml
@model IEnumerable<proyectoCRUD.Models.Libro>

@{
    ViewData["Title"] = "Biblioteca";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>ESTA ES LA SECCION DE LIBROS</h1>

<div class="container">

    @if(TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

    <div class="row">

        <div class="col-sm-6">
            <h3>LISTA DE LIBROS</h3>
        </div>

        <div class="col-sm-6">
            <a class= "btn btn-success d-block" asp-action="Create" asp-controller="Libros">NUEVO</a>
        </div>

</div>

    <div class="row">
            @if(Model.Count() > 0)
            {
                <table class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <td>@Html.DisplayNameFor(m => m.Id)</td>
                            <td>@Html.DisplayNameFor(m => m.Titulo)</td>
                            <td>@Html.DisplayNameFor(m => m.Descripcion)</td>
                            <td>@Html.DisplayNameFor(m => m.FechaPublicacion)</td>
                            <td>@Html.DisplayNameFor(m => m.Autor)</td>
                            <td>@Html.DisplayNameFor(m => m.PrecioLibro)</td>
                        </tr>
                    </thead>

                    <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                                    <td>@item.Id</td>
                                    <td>@item.Titulo</td>
                                    <td>@item.Descripcion</td>
                                    <td>@item.FechaPublicacion</td>
                                    <td>@item.Autor</td>
                                    <td>@item.PrecioLibro</td>
                                    <td>
                                        <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">EDITAR</a>
                                        <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">ELIMINAR</a>
                                    </td>
                        </tr>
                    }
                </tbody>

                </table>
        }
        else
        {
            <p>SIN REGISTROS PARA MOSTRAR!</p>
        }
    </div>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - proyectoCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">proyectoCRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">Libros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - proyectoCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>